name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
        working-directory: app
      - run: npm run lint
        working-directory: app

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
        working-directory: app
      - run: npm test
        working-directory: app

  build_app:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
        working-directory: app
      - run: npm run build --if-present
        working-directory: app

  docker_publish:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - uses: actions/checkout@v4
      - name: Login no GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Definir tags
        id: vars
        run: echo "TAG=ghcr.io/lessandrogs/devops-fase1-pipeline-iac:latest" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAG }}

  deploy_demo:
    runs-on: ubuntu-latest
    needs: docker_publish
    steps:
      - uses: actions/checkout@v4
      - name: Executar script de deploy
        run: bash scripts/deploy.sh
